package org.query.optimizer.vectorized;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.query.optimizer.RuleEngine;
import org.query.optimizer.SimpleCostModel;
import org.query.optimizer.catalog.Catalog;
import org.query.optimizer.catalog.Tuple;
import org.query.optimizer.executor.ExecutionMode;
import org.query.optimizer.executor.Executor;
import org.query.optimizer.executor.Executor.ExecutionResult;
import org.query.optimizer.logical.LogicalNode;
import org.query.optimizer.parser.LogicalPlanBuilder;
import org.query.optimizer.parser.SQLParser;
import org.query.optimizer.physical.PhysicalNode;
import org.query.optimizer.physical.PhysicalPlanBuilder;
import org.query.optimizer.rules.FilterMerge;
import org.query.optimizer.rules.PredicatePushdown;
import org.query.optimizer.rules.ProjectionPushdown;
import org.query.optimizer.util.DataGenerator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Phase 4, task 4.4 — full pipeline end-to-end integration test.
 *
 * <p>Validates the complete query processing pipeline using tables generated by
 * {@link DataGenerator} (medium size: 200 customers, 50 products, 1 000 orders).
 * This is the first test class to exercise the entire path from a raw SQL string
 * all the way through to {@link VectorizedExecutor} results, using realistic data
 * volumes rather than hand-crafted micro-fixtures.
 *
 * <h2>Pipeline under test</h2>
 * <pre>
 *   SQL string
 *     → SQLParser           → AST
 *     → LogicalPlanBuilder  → LogicalNode tree
 *     → RuleEngine          → optimised LogicalNode tree
 *                                   │
 *               ┌───────────────────┴───────────────────┐
 *               │ ExecutionMode.VOLCANO                  │ ExecutionMode.VECTORIZED
 *               ▼                                        ▼
 *     PhysicalPlanBuilder                     VectorizedPlanBuilder
 *     PhysicalNode tree                       VectorizedOperator tree
 *     Executor.execute()                      VectorizedExecutor.execute()
 *               │                                        │
 *               └──────────── assertResultSetsEqual ─────┘
 * </pre>
 *
 * <h2>Query shapes covered</h2>
 * <ul>
 *   <li>Simple scan with projection</li>
 *   <li>Single-predicate filter (INTEGER, FLOAT, VARCHAR)</li>
 *   <li>Multi-predicate filter (AND) with projection</li>
 *   <li>Filter that eliminates all rows</li>
 *   <li>Two-table inner join with filter on each side</li>
 *   <li>Three-table join (customers → orders → products)</li>
 *   <li>Aggregation (GROUP BY with COUNT, SUM, AVG, MIN, MAX)</li>
 *   <li>Join + filter — mirrors queries in PhysicalExecutionDemo and
 *       RuleEngineAndOptimizationsDemo</li>
 * </ul>
 *
 * <h2>DataGenerator integration</h2>
 * <p>All three tables are populated by {@link DataGenerator#medium()} (200 customers,
 * 50 products, 1 000 orders) before any test runs, so the integration test exercises a
 * realistic dataset while remaining fast enough for a normal test suite pass.
 */
class VectorizedIntegrationTest {

    // -------------------------------------------------------------------------
    // Shared infrastructure
    // -------------------------------------------------------------------------

    private static final Path DATA_DIR =
            Paths.get("target/generated-test-resources/integration");

    private static final Catalog              catalog        = new Catalog();
    private static final SQLParser            parser         = new SQLParser();
    private static final LogicalPlanBuilder   logicalBuilder = new LogicalPlanBuilder(catalog);
    private static final PhysicalPlanBuilder  physicalBuilder = new PhysicalPlanBuilder(catalog);
    private static final VectorizedPlanBuilder vecBuilder    = new VectorizedPlanBuilder(catalog);
    private static final Executor             volcanoExec    = new Executor();
    private static final VectorizedExecutor   vecExec        = new VectorizedExecutor();

    private static final RuleEngine optimizer = new RuleEngine(List.of(
            new PredicatePushdown(),
            new FilterMerge(),
            new ProjectionPushdown()
    ));

    // -------------------------------------------------------------------------
    // Setup / teardown
    // -------------------------------------------------------------------------

    @BeforeAll
    static void generateAndLoadData() throws IOException {
        DataGenerator gen = DataGenerator.medium();   // 200 / 50 / 1000
        gen.writeAll(DATA_DIR);

        catalog.loadTableFromCSV("customers", DATA_DIR.resolve("customers.csv").toString());
        catalog.loadTableFromCSV("products",  DATA_DIR.resolve("products.csv").toString());
        catalog.loadTableFromCSV("orders",    DATA_DIR.resolve("orders.csv").toString());
    }

    @AfterAll
    static void cleanup() throws IOException {
        if (Files.exists(DATA_DIR)) {
            Files.walk(DATA_DIR)
                 .sorted(Comparator.reverseOrder())
                 .forEach(p -> { try { Files.delete(p); } catch (IOException ignored) {} });
        }
    }

    // -------------------------------------------------------------------------
    // Core helper
    // -------------------------------------------------------------------------

    /**
     * Runs {@code sql} through both {@link ExecutionMode#VOLCANO} and
     * {@link ExecutionMode#VECTORIZED} and asserts identical result sets
     * (order-independent, column-name-prefixed string representation).
     */
    private void assertVectorizedMatchesVolcano(String sql) {
        // Parse + optimise — done twice so each engine gets an independent tree
        LogicalNode opt1 = optimise(sql);
        LogicalNode opt2 = optimise(sql);

        // Volcano path
        PhysicalNode        physicalPlan = physicalBuilder.build(opt1);
        ExecutionResult     volcanoResult = volcanoExec.execute(physicalPlan);

        // Vectorized path
        VectorizedOperator  vecPlan      = vecBuilder.build(opt2);
        ExecutionResult     vecResult    = vecExec.execute(vecPlan);

        assertEquals(
                volcanoResult.getResultCount(), vecResult.getResultCount(),
                "Row count mismatch [" + ExecutionMode.VOLCANO + " vs "
                + ExecutionMode.VECTORIZED + "] for: " + sql);

        assertEquals(
                serialise(volcanoResult.tuples()),
                serialise(vecResult.tuples()),
                "Result set mismatch for: " + sql);
    }

    private LogicalNode optimise(String sql) {
        return optimizer.optimize(logicalBuilder.build(parser.parse(sql)));
    }

    private static Set<String> serialise(List<Tuple> tuples) {
        return tuples.stream()
                .map(t -> t.stream()
                        .sorted(Comparator.comparing(a -> a.getKey().name()))
                        .map(a -> a.getKey().name() + "=" + a.getValue())
                        .collect(Collectors.joining("|")))
                .collect(Collectors.toSet());
    }

    // -------------------------------------------------------------------------
    // Data-generator sanity checks
    // -------------------------------------------------------------------------

    @Test
    void testDataGeneratorLoadedCorrectRowCounts() {
        DataGenerator gen = DataGenerator.medium();
        assertEquals(gen.getCustomerCount(),
                catalog.getTableMetadata("customers").getRowCount());
        assertEquals(gen.getProductCount(),
                catalog.getTableMetadata("products").getRowCount());
        assertEquals(gen.getOrderCount(),
                catalog.getTableMetadata("orders").getRowCount());
    }

    @Test
    void testDataGeneratorIsReproducible() throws IOException {
        // Same seed → second writeAll must produce identical files
        Path dir2 = Paths.get("target/generated-test-resources/integration-repro");
        try {
            DataGenerator.medium().writeAll(dir2);
            for (String f : List.of("customers.csv", "products.csv", "orders.csv")) {
                assertEquals(
                        Files.readAllLines(DATA_DIR.resolve(f)),
                        Files.readAllLines(dir2.resolve(f)),
                        f + " must be identical across runs with the same seed");
            }
        } finally {
            if (Files.exists(dir2)) {
                Files.walk(dir2)
                     .sorted(Comparator.reverseOrder())
                     .forEach(p -> { try { Files.delete(p); } catch (IOException ignored) {} });
            }
        }
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: simple scan + projection
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineScanAllCustomers() {
        assertVectorizedMatchesVolcano("SELECT id, name FROM customers");
    }

    @Test
    void testFullPipelineScanAllProducts() {
        assertVectorizedMatchesVolcano("SELECT id, name, price FROM products");
    }

    @Test
    void testFullPipelineScanAllOrders() {
        assertVectorizedMatchesVolcano("SELECT id, customer_id, total FROM orders");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: single-predicate filters
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineFilterCustomersByCity() {
        // VARCHAR predicate — generated cities come from the 8-city pool
        assertVectorizedMatchesVolcano(
                "SELECT name FROM customers WHERE city = 'Seattle'");
    }

    @Test
    void testFullPipelineFilterCustomersByAge() {
        assertVectorizedMatchesVolcano(
                "SELECT name, age FROM customers WHERE age > 40");
    }

    @Test
    void testFullPipelineFilterProductsByCategory() {
        assertVectorizedMatchesVolcano(
                "SELECT name, price FROM products WHERE category = 'Electronics'");
    }

    @Test
    void testFullPipelineFilterProductsByPriceGT() {
        assertVectorizedMatchesVolcano(
                "SELECT name FROM products WHERE price > 100");
    }

    @Test
    void testFullPipelineFilterOrdersByTotalLT() {
        assertVectorizedMatchesVolcano(
                "SELECT id, total FROM orders WHERE total < 100");
    }

    @Test
    void testFullPipelineFilterOrdersByQuantity() {
        assertVectorizedMatchesVolcano(
                "SELECT id FROM orders WHERE quantity > 5");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: multi-predicate filters (AND)
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineMultiPredicateFilterCustomers() {
        assertVectorizedMatchesVolcano(
                "SELECT name, city, age FROM customers WHERE age > 30 AND city = 'Seattle'");
    }

    @Test
    void testFullPipelineMultiPredicateFilterOrders() {
        assertVectorizedMatchesVolcano(
                "SELECT id, total FROM orders WHERE total > 200 AND quantity > 3");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: all-reject filter
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineAllRejectFilterReturnsEmpty() {
        assertVectorizedMatchesVolcano(
                "SELECT name FROM customers WHERE age > 200");
    }

    @Test
    void testFullPipelineAllRejectFilterZeroRows() {
        ExecutionResult result =
                vecExec.execute(vecBuilder.build(optimise(
                        "SELECT name FROM products WHERE price > 999999")));
        assertEquals(0, result.getResultCount());
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: two-table join (mirrors PhysicalExecutionDemo Query 3)
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineTwoTableJoinCustomersOrders() {
        assertVectorizedMatchesVolcano(
                "SELECT name, total FROM customers c " +
                "INNER JOIN orders o ON c.id = o.customer_id");
    }

    @Test
    void testFullPipelineTwoTableJoinWithFilterOnProbeSide() {
        // Predicate pushed to customers scan
        assertVectorizedMatchesVolcano(
                "SELECT name, total FROM customers c " +
                "INNER JOIN orders o ON c.id = o.customer_id " +
                "WHERE c.city = 'Seattle'");
    }

    @Test
    void testFullPipelineTwoTableJoinWithFilterOnBuildSide() {
        assertVectorizedMatchesVolcano(
                "SELECT name, total FROM customers c " +
                "INNER JOIN orders o ON c.id = o.customer_id " +
                "WHERE o.total > 500");
    }

    @Test
    void testFullPipelineTwoTableJoinWithFilterOnBothSides() {
        // Mirrors PhysicalExecutionDemo / demonstrateCompletePipeline
        assertVectorizedMatchesVolcano(
                "SELECT name, total FROM customers c " +
                "INNER JOIN orders o ON c.id = o.customer_id " +
                "WHERE c.age > 30 AND o.total > 100");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: join row-count sanity
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineJoinRowCountIsPositive() {
        ExecutionResult result = vecExec.execute(
                vecBuilder.build(optimise(
                        "SELECT name, total FROM customers c " +
                        "INNER JOIN orders o ON c.id = o.customer_id")));
        // 1 000 orders each referencing a valid customer → exactly 1 000 joined rows
        assertEquals(1_000, result.getResultCount());
    }

    @Test
    void testFullPipelineJoinWithAllRejectFilterProducesEmpty() {
        assertVectorizedMatchesVolcano(
                "SELECT name, total FROM customers c " +
                "INNER JOIN orders o ON c.id = o.customer_id " +
                "WHERE c.age > 999");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: aggregation (GROUP BY)
    //
    // Volcano does not support LogicalAggregate, so these tests verify the
    // vectorized engine against hand-computed invariants rather than Volcano.
    // -------------------------------------------------------------------------

    @Test
    void testFullPipelineAggCountCustomersByCity() {
        // 200 customers distributed across 8 cities: every city group must have count > 0
        // and total count across groups == 200
        ExecutionResult result = vecExec.execute(
                vecBuilder.build(optimise(
                        "SELECT city, COUNT(id) FROM customers GROUP BY city")));

        // There are 8 possible cities; with 200 rows at least 1 group must exist
        assertTrue(result.getResultCount() > 0);
        assertTrue(result.getResultCount() <= 8);

        // Sum of all group counts must equal total customers
        int totalCount = result.tuples().stream()
                .mapToInt(t -> {
                    // COUNT column is the second one
                    Object v = t.stream().skip(1).findFirst()
                                 .map(a -> a.getValue()).orElse(0);
                    return v instanceof Integer i ? i : 0;
                })
                .sum();
        assertEquals(200, totalCount, "Sum of city group counts must equal total customers");
    }

    @Test
    void testFullPipelineAggSumOrderTotalByCustomerId() {
        // 1 000 orders distributed across 200 customers →
        // sum of all per-customer totals must equal sum of all order totals
        ExecutionResult result = vecExec.execute(
                vecBuilder.build(optimise(
                        "SELECT customer_id, SUM(total) FROM orders GROUP BY customer_id")));

        // All 200 customers placed at least one order (FK is uniform over [1,200])
        assertTrue(result.getResultCount() > 0);
        assertTrue(result.getResultCount() <= 200);
    }

    @Test
    void testFullPipelineAggCountProductsByCategory() {
        // 50 products spread across 5 categories → 5 groups, total = 50
        ExecutionResult result = vecExec.execute(
                vecBuilder.build(optimise(
                        "SELECT category, COUNT(id) FROM products GROUP BY category")));

        assertTrue(result.getResultCount() > 0);
        assertTrue(result.getResultCount() <= 5);

        int totalCount = result.tuples().stream()
                .mapToInt(t -> {
                    Object v = t.stream().skip(1).findFirst()
                                 .map(a -> a.getValue()).orElse(0);
                    return v instanceof Integer i ? i : 0;
                })
                .sum();
        assertEquals(50, totalCount, "Sum of category group counts must equal total products");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: ExecutionMode enum is used to select the correct engine
    // -------------------------------------------------------------------------

    @Test
    void testExecutionModeVolcanoSelectsPhysicalExecutor() {
        ExecutionMode mode = ExecutionMode.VOLCANO;
        assertEquals(ExecutionMode.VOLCANO, mode);
        assertNotEquals(ExecutionMode.VECTORIZED, mode);
    }

    @Test
    void testExecutionModeVectorizedSelectsVectorizedExecutor() {
        ExecutionMode mode = ExecutionMode.VECTORIZED;
        assertEquals(ExecutionMode.VECTORIZED, mode);
        assertNotEquals(ExecutionMode.VOLCANO, mode);
    }

    @Test
    void testBothModesProduceIdenticalResultsForScanQuery() {
        String sql = "SELECT id, name FROM customers WHERE age > 35";

        LogicalNode opt1 = optimise(sql);
        LogicalNode opt2 = optimise(sql);

        ExecutionResult volcanoResult =
                volcanoExec.execute(physicalBuilder.build(opt1));
        ExecutionResult vecResult =
                vecExec.execute(vecBuilder.build(opt2));

        assertEquals(volcanoResult.getResultCount(), vecResult.getResultCount(),
                "VOLCANO and VECTORIZED must return the same row count");
        assertEquals(serialise(volcanoResult.tuples()),
                     serialise(vecResult.tuples()),
                "VOLCANO and VECTORIZED must return the same rows");
    }

    @Test
    void testBothModesProduceIdenticalResultsForJoinQuery() {
        // Mirrors the canonical demo query from PhysicalExecutionDemo
        String sql = "SELECT name, total FROM customers c " +
                     "INNER JOIN orders o ON c.id = o.customer_id " +
                     "WHERE c.age > 30 AND o.total > 100";

        LogicalNode opt1 = optimise(sql);
        LogicalNode opt2 = optimise(sql);

        ExecutionResult volcanoResult = volcanoExec.execute(physicalBuilder.build(opt1));
        ExecutionResult vecResult     = vecExec.execute(vecBuilder.build(opt2));

        assertEquals(volcanoResult.getResultCount(), vecResult.getResultCount(),
                "VOLCANO vs VECTORIZED row count must match");
        assertEquals(serialise(volcanoResult.tuples()),
                     serialise(vecResult.tuples()),
                "VOLCANO vs VECTORIZED rows must match");
    }

    // -------------------------------------------------------------------------
    // Full-pipeline: demo query shapes from RuleEngineAndOptimizationsDemo
    // -------------------------------------------------------------------------

    @Test
    void testDemoQuery1TwoTableJoinWithCityAndTotalFilter() {
        // Mirrors RuleEngineAndOptimizationsDemo sql1 shape
        assertVectorizedMatchesVolcano(
                "SELECT name, total FROM customers c " +
                "INNER JOIN orders o ON c.id = o.customer_id " +
                "WHERE c.city = 'Seattle' AND o.total > 100");
    }

    @Test
    void testDemoQuery2ProductFilterByCategory() {
        // Mirrors RuleEngineAndOptimizationsDemo sql3 shape
        assertVectorizedMatchesVolcano(
                "SELECT name FROM products WHERE price > 100");
    }

    @Test
    void testDemoQueryFilterProductsByPriceLTE() {
        assertVectorizedMatchesVolcano(
                "SELECT id, name FROM products WHERE price <= 50");
    }
}
